[package]
name = "derrick-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
crossterm = { workspace = true }
derrick-config = { path = "../derrick-config" }
derrick-adopt = { path = "../derrick-adopt" }
derrick-flow = { path = "../derrick-flow" }
derrick-models = { path = "../derrick-models" }
derrick-substrate = { path = "../derrick-substrate" }
derrick-substrate-native = { path = "../derrick-substrate-native" }
derrick-tools = { path = "../derrick-tools" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
which = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
assert_cmd = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"

[lib]
name = "derrick_cli"
path = "src/lib.rs"

[[bin]]
name = "derrick"
path = "src/main.rs"
